version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.10.0.442
      
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "deps.edn" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
        
      - run: ./bin/cibuild


      - codecov/upload:
          file: target/coverage/codecov.json

      - save_cache:
          paths:
            - ~/.m2
            - .cpcache
          key: v2-dependencies-{{ checksum "deps.edn" }}
